import type { Metadata } from "next";
import { Analytics } from "@vercel/analytics/react"
import { SpeedInsights } from "@vercel/speed-insights/next"
import { AppRouterCacheProvider } from '@mui/material-nextjs/v13-appRouter';
import { Container, CssBaseline, Skeleton } from "@mui/material";
import { Suspense } from "react";

export const metadata: Metadata = {
    title: "CLUBLE",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: {
    children: React.ReactNode;
}) {
    return (
        <html lang="pt-br">
            <body>
                <Analytics />
                <SpeedInsights />
                <CssBaseline />
                <AppRouterCacheProvider>
                    <Container maxWidth="sm">
                        <Suspense fallback={
                            <Skeleton />
                        }>
                            {children}
                        </Suspense>
                    </Container>
                </AppRouterCacheProvider>
            </body>
        </html>
    );
}
