import type { Metadata } from "next";
import { SpeedInsights } from "@vercel/speed-insights/next"
import { AppRouterCacheProvider } from '@mui/material-nextjs/v13-appRouter';
import { CssBaseline } from "@mui/material";

export const metadata: Metadata = {
    title: "CLUBLE",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
  }: {
    children: React.ReactNode;
  }) {
    return (
        <html lang="pt-br">
            <body>
            <SpeedInsights/>
                <CssBaseline />
                <AppRouterCacheProvider>
                    {children}
                </AppRouterCacheProvider>
            </body>
        </html>
    );
}
